#!/bin/sh
### BEGIN INIT INFO
# Provides:          greylist
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop the greylistd(8) daemon.
### END INIT INFO
########################################################################
### FILE:	/etc/init.d/greylist
########################################################################

client=/usr/bin/greylist
daemon=/usr/sbin/greylistd
rundir=/var/run/greylistd
datadir=/var/lib/greylistd
pidfile=$rundir/pid
socket=$rundir/socket
user=greylist
group=greylist

# See if the daemon is present
test -x "$daemon" || exit 0

# Make sure /var/run/greylistd exists (/var/run may be a tmpfs)
test -d "$rundir" || {
    mkdir -p "$rundir"
    chown "$user:$group" "$rundir"
}

case "$1" in
    start)
	if [ -e "$socket" ]
	then
	    echo "$0:"
	    echo "  Another instance of \`${daemon##*/}' seems to be running."
	    echo "  If this is not the case, please remove \"$socket\"."
	    exit 1
	fi

	echo -n "Starting greylisting daemon: "
	start-stop-daemon --start --background \
	    --chuid "$user" \
	    --pidfile "$pidfile" --make-pidfile \
	    --exec "$daemon" &&
	    echo "${daemon##*/}."
	;;


    stop)
	echo -n "Stopping greylisting daemon: "
	start-stop-daemon --stop --pidfile "$pidfile" &&
	    rm -f "$pidfile" &&
	    echo "${daemon##*/}."
	;;


    reload|force-reload)
	"$client" reload
	;;

    status)
	"$client" stats
	;;


    restart)
	$0 stop
	sleep 1
	$0 start
	;;


    *)
	echo "Usage: $0 {start|stop|restart|reload|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0

